### ISSUE TITLE
Building on Linux

### ISSUE THREAD

**Issue by fstonedahl** [StanWarford/pep9#4]
I'm a professor at Augustana College who will be working with @wcstowe to try to create a Linux terminal version of Pep/9.  

The build process is a bit murky right now (is the repository missing the file **macdeployqt**?)

In general, any advice regarding the build process for Linux would be appreciated!

**Comment by StanWarford** [comment]
Hi Forrest,

This is good news. I have always wanted a terminal version based on the Qt code but never had the resources to do it. Matt should be able to give some guidance.

—jsw

J. Stanley Warford
Professor of Computer Science
Pepperdine University
Malibu, CA 90263
310-506-4332
Stan.Warford@pepperdine.edu

**Comment by fstonedahl** [comment]
Update:  We noticed that a Makefile is referenced in the **.gitignore** file, along with a number of .h files (which might or might not be important?).  Is there a working Makefile which just isn't up on GitHub at present?

**Comment by Matthew-McRaven** [comment]
Hello,

Thanks for your interest in creating a terminal based application!

For Pep/8, there is an existing terminal application. The sources are available [here](http://computersystemsbook.com/4th-edition/pep8/). This might give you some inspiration for the UI on the terminal.

You also caught us in the middle of a refactor of all the Pep/9 applications. Current work on the project is going on over in the [Pep9Micro repository](https://github.com/StanWarford/pep9micro/). 

Basing the terminal application on the work over there should make designing the terminal application easier, as much of the model functionality has been moved from the UI's to independent classes. I can also provide detailed instructions on how to integrate a new terminal UI with the existing model source code.

As for building on Linux, I highly recommend using Qt Creator. Opening up the If you are building from command line, I can provide detailed instructions after my linux vm is updated.

The MacDeployQT tool does not need to be installed on a Linux target, as it is only referenced from inside a conditional qmake block that is only activated on a Mac target. It is included as part of the Qt Installer Framework 3.0 (an optional add-on when installing the Qt Libraries) on Mac.

**Comment by Matthew-McRaven** [comment]
Building from command line in Linux should just require you execute `cd Pep9 && qmake && make`.  The reason many files (such as the Makefile) are ignored is that they are generated by `qmake` and therefore it is not useful to track them.

If you open Pep9.pro in Qt Creator, the project it will automatically compile all files in a shadowed build directory (something of the form build-pep9-kit_name_here). 

If you choose to build from command line, I recommend the following build process instead of building in the Pep9 directory: 

- Make a build directory in a sibling directory to Pep9.
- Change to that directory.
- Execute `qmake` with the path to Pep9.
- Run `make` as normal. It is possible`qmake` will have already executed `make` for you, but it is helpful to run just in case.

Anytime you add new files to the project, modify qt resources, ui files you must re-run `qmake path/to/pep9` then `make` for all of your changes to be reflected.

![screen shot 2019-03-06 at 16 26 38](https://user-images.githubusercontent.com/35609985/53923315-b58a7700-402c-11e9-8692-7a87005489c4.png)

**Comment by wcstowe** [comment]
Hello,
I am working with Dr. Stonedahl on this project. I have cloned the pep9 files, and have tried qmake, and gives the error 'Project ERROR: Unknown module(s) in QT: webenginewidgets.' Also, disregarding this, I tried to run make on the files, and it gives an error on all headers in the source code that start with "QWidget." I've removed those, and it seems to make some more progress in the make file, until it gets to compiling the byteconverter files where it spits out all kinds of C++ errors. Any ideas on how to fix this?

**Comment by Matthew-McRaven** [comment]
Hello,

QtWebEngineWidgets is not installed by default when installing Qt. If installing via the maintenance tool, one must seperately install the Qt WebEngine package. This will resolve the errors. Highlighted in the below screenshot is the package that must be installed.

<img width="324" alt="Screen Shot 2019-03-12 at 10 19 28" src="https://user-images.githubusercontent.com/35609985/54221291-73d85100-44b0-11e9-816a-4a5e60f5b8e9.png">

Changing Qt versions and managing which components are installed is not easy from command line. I highly recommend downloading the [Qt Installer for Linux](http://download.qt.io/official_releases/qt/5.12/5.12.1/qt-opensource-linux-x64-5.12.1.run), and doing all of your development in Qt Creator.

If you choose to build from command line instead of Qt Creator, you will have to figure out how to install the web engine widgets packages.

**Comment by Matthew-McRaven** [comment]
As far as the C++ error, you'd have to upload a log of the compiler output. 

I am able to build the Pep/9 source on Ubuntu 18.04 from Qt Creator from an Qt 5.12 instance installed via the maintenance tool. After setting up my terminal environment to point to this Qt instance (using the [QtChooser](https://www.systutorials.com/docs/linux/man/1-qtchooser/) tool), I am also able to run `qmake && make` and have Pep9 compile successfully.

**Comment by StanWarford** [comment]
I would not expect the command line version to use Qt WebEngine, because the command line version would not have a web based help system. Most command line apps have a -help flag that gives documentation as a text character stream.

J. Stanley Warford
Professor of Computer Science
Pepperdine University
Malibu, CA 90263
310-506-4332
Stan.Warford@pepperdine.edu

**Comment by fstonedahl** [comment]
Yes, I think ideally the command line version might end up cutting all the dependencies on Qt entirely.  I'm not sure exactly how easy that will be to accomplish, depending on how deeply intertwined the UI code is with the engine.  As a first step, we were just trying to get the whole project to build on Linux as is, and then figure out how to disentangle the core assembler & interpreter/simulator code from the UI.

At some point we'll need to tackle the question of how to build it both ways (UI & command-line).  I'm guessing this will involve us learning more about the **qmake** build system, to give it an option to build it one way or the other.

**Comment by EmilyDimpfl** [comment]
I think its unlikely that you'll cut (or perhaps want to cut?) all Qt dependencies - you certainly won't need the UI libraries, but we use Qt types (such as QVector, QSet, QString, QTextStream...) for a lot of things, so stripping out ALL Qt dependencies is unnecessary, and a pretty significant effort that additionally makes maintaining both versions more difficult.

There's a lot of UI specific code in the codebase, and I'm pretty sure you could compose a command line tool out of a small subset of the classes - depending on how you want to interact with the tool on the command line (ie, batch only, pre/postcondition checking for automated homework checking, versus a more complex ncurses interface, or something else), you'd need more or less of the codebase, but for a minimal simulation, you could make do with a handful of classes, essentially as-is:

* asm.cpp/h
* code.cpp/h
* enu.h
* pep.cpp/h
* sim.cpp/h

You'd need to rewrite a bunch of the application logic in MainWindow and CpuPane to drive the simulation as well.

**Comment by fstonedahl** [comment]
Thanks @EmilyDimpfl  - that's very helpful.  

Our primary goal for this project is a batch-only interface, consisting of two commands:  1) an assembler that takes in .pep files and produces .pepo files (or readable error messages if that fails), and 2) an interpreter/simulator for .pepo files that reads from standard input and prints to standard output.

**Comment by wcstowe** [comment]
I've gotten the .pro file to accept the Qt += webenginewidgets. The problem I'm having is in the file "ui_helpdialog.h." When I add the line "#include <QWebEngineView>", it does not recognize it.

**Comment by EmilyDimpfl** [comment]
@fstonedahl Assembly is pretty straightforward. This is the main chunk that kicks that off:

https://github.com/StanWarford/pep9/blob/master/mainwindow.cpp#L477

This is the meat of the actual assembly:

https://github.com/StanWarford/pep9/blob/master/sourcecodepane.cpp#L59

(which you could use nearly in its entirety for a command line program)

Simulation is pretty straightforward, especially if you're just doing batch runs and no interactive input and so on. This is the code that kicks off a "run":

https://github.com/StanWarford/pep9/blob/master/mainwindow.cpp#L965

This is what drives the actual loop-until-stop:

https://github.com/StanWarford/pep9/blob/master/cpupane.cpp#L195

Without the UI code, this boils down to:

```
    while (true) {
        if (Sim::vonNeumannStep(errorString)) {
            emit vonNeumannStepped();
            if (Sim::outputBuffer.length() == 1) {
                emit appendOutput(Sim::outputBuffer);
                Sim::outputBuffer = "";
            }
        }
        else {
            QMessageBox::warning(0, "Pep/9", errorString);
            emit executionComplete();
            return;
        }
        if (Pep::decodeMnemonic[Sim::instructionSpecifier] == Enu::STOP) {
            emit executionComplete();
            return;
        }
    }
```

This essentially just outputs new output during the run, and then stops if there's an error or STOP instruction. We use the mediator design pattern (https://en.wikipedia.org/wiki/Mediator_pattern) so the CPU widget tells the main window that it did some work (via emit), and then the main window tells the appropriate widgets to update their state.

Initializing the machine state is also pretty straightforward, and is kicked off in the main window:

https://github.com/StanWarford/pep9/blob/master/mainwindow.cpp#L44

A lot of this is UI stuff, compared to a small amount of machine state:

```
Pep::initEnumMnemonMaps();
Pep::initAddrModesMap();
Pep::initMnemonicMaps();
Pep::initDecoderTables();

Sim::nBit = false;
Sim::zBit = false;
Sim::vBit = false;
Sim::cBit = false;

Sim::accumulator = 0;
Sim::indexRegister = 0;
Sim::stackPointer = 0; // or Sim::readWord(Pep::dotBurnArgument - 7)?
Sim::programCounter = 0;

// Install OS into memory
Pep::memAddrssToAssemblerListing = &Pep::memAddrssToAssemblerListingOS;
Pep::listingRowChecked = &Pep::listingRowCheckedOS;
if (sourceCodePane->installDefaultOs()) {
    ui->statusbar->showMessage("OS installed", 4000);
}
else {
    ui->statusbar->showMessage("OS assembly failed", 4000);
}
```

(There might be a little more initialization I'm forgetting at the moment, but the entire machine state can be found in sim.cpp:)

https://github.com/StanWarford/pep9/blob/master/sim.cpp#L29

Pretty straightforward to re-implement the simulation, compared to the many lines of UI code :)

@wcstowe: regarding ui_helpdialog.h, that's a `qmake` generated file that shouldn't be edited by hand. Try running qmake again?

(edited for markdown fix)

**Comment by StanWarford** [comment]
We are in the process of refactoring all the Pep/9 applications into one suite of code, so we can use common code among all the apps. In the process, we have developed a command line version of Pep/9 that we have used internally for a few weeks now. Code for the suite, including the command line version pep9Term is at

https://github.com/StanWarford/pep9suite/releases <https://github.com/StanWarford/pep9suite/releases>

**Comment by StanWarford** [comment]
Command line versions for Windows, MacOS, and Linux are now available at

[http://computersystemsbook.com/5th-edition/pep9/](http://computersystemsbook.com/5th-edition/pep9/)
